[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
env_logger = "0.8"
serde = { version = "1", features = [ "derive" ] }
rmp-serde = "0.15"
ir = { path = "../ir" }

