[package]
name = "asm"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10"
anyhow = "1"
log = "0.4"
env_logger = "0.8"
serde = { version = "1", features = [ "derive" ] }
rmp-serde = "0.15"
ron = "0.7"
ir = { path = "../ir" }

